# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..commons.types.entity_id_base import EntityIdBase
from ..commons.types.entity_id_without_agent import EntityIdWithoutAgent
from ..commons.types.entity_type import EntityType
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawIntelligentFieldsClient, RawIntelligentFieldsClient
from .types.enum_option import EnumOption
from .types.intelligent_field_detail_response import IntelligentFieldDetailResponse
from .types.intelligent_field_response import IntelligentFieldResponse
from .types.intelligent_field_status import IntelligentFieldStatus
from .types.intelligent_field_type import IntelligentFieldType
from .types.intelligent_field_value_entity_filter import IntelligentFieldValueEntityFilter
from .types.intelligent_field_value_field_filter import IntelligentFieldValueFieldFilter
from .types.intelligent_field_value_search_response import IntelligentFieldValueSearchResponse
from .types.intelligent_field_value_sort_field import IntelligentFieldValueSortField

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IntelligentFieldsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIntelligentFieldsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIntelligentFieldsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIntelligentFieldsClient
        """
        return self._raw_client

    def create_or_update(
        self,
        *,
        field_id: EntityIdBase,
        entity_type: EntityType,
        name: str,
        validation_type: IntelligentFieldType,
        definition: str,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Create a new intelligent field. Intelligent fields are used to store custom LLM-generated values on entities like conversations or events.

        Parameters
        ----------
        field_id : EntityIdBase
            ID that uniquely identifies this intelligent field

        entity_type : EntityType
            Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.

        name : str
            Display name for the intelligent field

        validation_type : IntelligentFieldType
            Result type hint used for schema generation, UI, and validation.

            - STRING / MULTILINE: single string value
            - MULTI_SELECT: multiple values
            - BOOLEAN: boolean value
            - NUMBER: numeric value

            Note: for single select, use STRING/NUMBER with a list of enumOptions.

        definition : str
            Definition used by the LLM when generating this field's value

        variant_id : typing.Optional[EntityIdWithoutAgent]
            ID of the agent variant that created this field, if applicable

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        from mavenagi import MavenAGI
        from mavenagi.commons import EntityIdBase
        from mavenagi.intelligent_fields import EnumOption

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.intelligent_fields.create_or_update(
            field_id=EntityIdBase(
                reference_id="ticket-priority",
            ),
            name="Ticket Priority",
            description="The priority of the conversation based on urgency",
            entity_type="CONVERSATION",
            validation_type="STRING",
            enum_options=[
                EnumOption(
                    value="HIGH",
                    label="High Priority",
                ),
                EnumOption(
                    value="MEDIUM",
                    label="Medium Priority",
                ),
                EnumOption(
                    value="LOW",
                    label="Low Priority",
                ),
            ],
            definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
        )
        """
        _response = self._raw_client.create_or_update(
            field_id=field_id,
            entity_type=entity_type,
            name=name,
            validation_type=validation_type,
            definition=definition,
            variant_id=variant_id,
            description=description,
            enum_options=enum_options,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldDetailResponse:
        """
        Get an intelligent field by its supplied ID

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to get. All other entity ID fields are inferred from the request.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to get. If not provided the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldDetailResponse

        Examples
        --------
        from mavenagi import MavenAGI

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.intelligent_fields.get(
            field_reference_id="ticket-priority",
        )
        """
        _response = self._raw_client.get(field_reference_id, app_id=app_id, request_options=request_options)
        return _response.data

    def patch(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = OMIT,
        definition: typing.Optional[str] = OMIT,
        status: typing.Optional[IntelligentFieldStatus] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        variant_id: typing.Optional[EntityIdBase] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Patch an intelligent field. Can be used to update the definition, status, or other mutable properties.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to patch.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to update. If not provided the ID of the calling app will be used.

        definition : typing.Optional[str]
            The definition of the intelligent field. This text will be influential in guiding the LLM to produce the desired results.

        status : typing.Optional[IntelligentFieldStatus]
            The lifecycle state for whether this field is evaluated by workflows. Use INACTIVE to deactivate.

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Updated enum options for select/multi-select fields. Omit to leave unchanged. The new list must be a superset of the existing options (add-only; removals are rejected).

        variant_id : typing.Optional[EntityIdBase]
            ID of the agent variant that this field belongs to, if applicable

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        from mavenagi import MavenAGI

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.intelligent_fields.patch(
            field_reference_id="ticket-priority",
            definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
        )
        """
        _response = self._raw_client.patch(
            field_reference_id,
            app_id=app_id,
            definition=definition,
            status=status,
            description=description,
            enum_options=enum_options,
            variant_id=variant_id,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Soft delete an intelligent field. Only INACTIVE fields can be deleted.

        Deleted fields are excluded from search results but can still be retrieved by ID.
        Creating a new field with the same referenceId as a deleted field will overwrite
        the deleted field and restore it to INACTIVE status.

        Deleted fields cannot be modified.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to delete.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant reference ID of the intelligent field to delete.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        from mavenagi import MavenAGI

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.intelligent_fields.delete(
            field_reference_id="ticket-priority",
        )
        """
        _response = self._raw_client.delete(
            field_reference_id,
            app_id=app_id,
            variant_reference_id=variant_reference_id,
            variant_app_id=variant_app_id,
            request_options=request_options,
        )
        return _response.data

    def search_values(
        self,
        *,
        field_filter: typing.Optional[IntelligentFieldValueFieldFilter] = OMIT,
        entity_filter: typing.Optional[IntelligentFieldValueEntityFilter] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        created_before: typing.Optional[dt.datetime] = OMIT,
        include_unknown_values: typing.Optional[bool] = OMIT,
        sort: typing.Optional[IntelligentFieldValueSortField] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        page: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        sort_desc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldValueSearchResponse:
        """
        Search computed values for intelligent fields across entities. Supports filtering by field properties and target entity.

        Parameters
        ----------
        field_filter : typing.Optional[IntelligentFieldValueFieldFilter]
            Filter by properties of the intelligent field definition. If not provided, returns values for all fields.

        entity_filter : typing.Optional[IntelligentFieldValueEntityFilter]
            Filter by properties of the target entity. If not provided, returns values across all entities.

        created_after : typing.Optional[dt.datetime]
            Filter values computed on or after this timestamp

        created_before : typing.Optional[dt.datetime]
            Filter values computed on or before this timestamp

        include_unknown_values : typing.Optional[bool]
            Whether to include results where the LLM could not determine a value (value is null). Defaults to false.

        sort : typing.Optional[IntelligentFieldValueSortField]
            Field to sort by. Defaults to CREATED_AT.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            Filter to values generated by a specific agent variant. If not provided, returns values from all variants.

        page : typing.Optional[int]
            Page number to return, defaults to 0

        size : typing.Optional[int]
            The size of the page to return, defaults to 20. Max 1000.

        sort_desc : typing.Optional[bool]
            Whether to sort descending, defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldValueSearchResponse

        Examples
        --------
        from mavenagi import MavenAGI
        from mavenagi.commons import EntityId
        from mavenagi.intelligent_fields import (
            IntelligentFieldValueEntityFilter,
            IntelligentFieldValueFieldFilter,
        )

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.intelligent_fields.search_values(
            field_filter=IntelligentFieldValueFieldFilter(
                field_ids=[
                    EntityId(
                        reference_id="ticket-priority",
                        app_id="zendesk",
                        type="INTELLIGENT_FIELD",
                        organization_id="acme",
                        agent_id="support",
                    )
                ],
            ),
            entity_filter=IntelligentFieldValueEntityFilter(
                entity_ids=[
                    EntityId(
                        reference_id="conv-123",
                        app_id="zendesk",
                        type="CONVERSATION",
                        organization_id="acme",
                        agent_id="support",
                    )
                ],
            ),
            page=0,
            size=20,
            sort="CREATED_AT",
            sort_desc=True,
        )
        """
        _response = self._raw_client.search_values(
            field_filter=field_filter,
            entity_filter=entity_filter,
            created_after=created_after,
            created_before=created_before,
            include_unknown_values=include_unknown_values,
            sort=sort,
            variant_id=variant_id,
            page=page,
            size=size,
            sort_desc=sort_desc,
            request_options=request_options,
        )
        return _response.data


class AsyncIntelligentFieldsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIntelligentFieldsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIntelligentFieldsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIntelligentFieldsClient
        """
        return self._raw_client

    async def create_or_update(
        self,
        *,
        field_id: EntityIdBase,
        entity_type: EntityType,
        name: str,
        validation_type: IntelligentFieldType,
        definition: str,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Create a new intelligent field. Intelligent fields are used to store custom LLM-generated values on entities like conversations or events.

        Parameters
        ----------
        field_id : EntityIdBase
            ID that uniquely identifies this intelligent field

        entity_type : EntityType
            Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.

        name : str
            Display name for the intelligent field

        validation_type : IntelligentFieldType
            Result type hint used for schema generation, UI, and validation.

            - STRING / MULTILINE: single string value
            - MULTI_SELECT: multiple values
            - BOOLEAN: boolean value
            - NUMBER: numeric value

            Note: for single select, use STRING/NUMBER with a list of enumOptions.

        definition : str
            Definition used by the LLM when generating this field's value

        variant_id : typing.Optional[EntityIdWithoutAgent]
            ID of the agent variant that created this field, if applicable

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI
        from mavenagi.commons import EntityIdBase
        from mavenagi.intelligent_fields import EnumOption

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.intelligent_fields.create_or_update(
                field_id=EntityIdBase(
                    reference_id="ticket-priority",
                ),
                name="Ticket Priority",
                description="The priority of the conversation based on urgency",
                entity_type="CONVERSATION",
                validation_type="STRING",
                enum_options=[
                    EnumOption(
                        value="HIGH",
                        label="High Priority",
                    ),
                    EnumOption(
                        value="MEDIUM",
                        label="Medium Priority",
                    ),
                    EnumOption(
                        value="LOW",
                        label="Low Priority",
                    ),
                ],
                definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_or_update(
            field_id=field_id,
            entity_type=entity_type,
            name=name,
            validation_type=validation_type,
            definition=definition,
            variant_id=variant_id,
            description=description,
            enum_options=enum_options,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldDetailResponse:
        """
        Get an intelligent field by its supplied ID

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to get. All other entity ID fields are inferred from the request.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to get. If not provided the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldDetailResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.intelligent_fields.get(
                field_reference_id="ticket-priority",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(field_reference_id, app_id=app_id, request_options=request_options)
        return _response.data

    async def patch(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = OMIT,
        definition: typing.Optional[str] = OMIT,
        status: typing.Optional[IntelligentFieldStatus] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        variant_id: typing.Optional[EntityIdBase] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Patch an intelligent field. Can be used to update the definition, status, or other mutable properties.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to patch.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to update. If not provided the ID of the calling app will be used.

        definition : typing.Optional[str]
            The definition of the intelligent field. This text will be influential in guiding the LLM to produce the desired results.

        status : typing.Optional[IntelligentFieldStatus]
            The lifecycle state for whether this field is evaluated by workflows. Use INACTIVE to deactivate.

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Updated enum options for select/multi-select fields. Omit to leave unchanged. The new list must be a superset of the existing options (add-only; removals are rejected).

        variant_id : typing.Optional[EntityIdBase]
            ID of the agent variant that this field belongs to, if applicable

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.intelligent_fields.patch(
                field_reference_id="ticket-priority",
                definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch(
            field_reference_id,
            app_id=app_id,
            definition=definition,
            status=status,
            description=description,
            enum_options=enum_options,
            variant_id=variant_id,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldResponse:
        """
        Soft delete an intelligent field. Only INACTIVE fields can be deleted.

        Deleted fields are excluded from search results but can still be retrieved by ID.
        Creating a new field with the same referenceId as a deleted field will overwrite
        the deleted field and restore it to INACTIVE status.

        Deleted fields cannot be modified.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to delete.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant reference ID of the intelligent field to delete.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.intelligent_fields.delete(
                field_reference_id="ticket-priority",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            field_reference_id,
            app_id=app_id,
            variant_reference_id=variant_reference_id,
            variant_app_id=variant_app_id,
            request_options=request_options,
        )
        return _response.data

    async def search_values(
        self,
        *,
        field_filter: typing.Optional[IntelligentFieldValueFieldFilter] = OMIT,
        entity_filter: typing.Optional[IntelligentFieldValueEntityFilter] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        created_before: typing.Optional[dt.datetime] = OMIT,
        include_unknown_values: typing.Optional[bool] = OMIT,
        sort: typing.Optional[IntelligentFieldValueSortField] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        page: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        sort_desc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IntelligentFieldValueSearchResponse:
        """
        Search computed values for intelligent fields across entities. Supports filtering by field properties and target entity.

        Parameters
        ----------
        field_filter : typing.Optional[IntelligentFieldValueFieldFilter]
            Filter by properties of the intelligent field definition. If not provided, returns values for all fields.

        entity_filter : typing.Optional[IntelligentFieldValueEntityFilter]
            Filter by properties of the target entity. If not provided, returns values across all entities.

        created_after : typing.Optional[dt.datetime]
            Filter values computed on or after this timestamp

        created_before : typing.Optional[dt.datetime]
            Filter values computed on or before this timestamp

        include_unknown_values : typing.Optional[bool]
            Whether to include results where the LLM could not determine a value (value is null). Defaults to false.

        sort : typing.Optional[IntelligentFieldValueSortField]
            Field to sort by. Defaults to CREATED_AT.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            Filter to values generated by a specific agent variant. If not provided, returns values from all variants.

        page : typing.Optional[int]
            Page number to return, defaults to 0

        size : typing.Optional[int]
            The size of the page to return, defaults to 20. Max 1000.

        sort_desc : typing.Optional[bool]
            Whether to sort descending, defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IntelligentFieldValueSearchResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI
        from mavenagi.commons import EntityId
        from mavenagi.intelligent_fields import (
            IntelligentFieldValueEntityFilter,
            IntelligentFieldValueFieldFilter,
        )

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.intelligent_fields.search_values(
                field_filter=IntelligentFieldValueFieldFilter(
                    field_ids=[
                        EntityId(
                            reference_id="ticket-priority",
                            app_id="zendesk",
                            type="INTELLIGENT_FIELD",
                            organization_id="acme",
                            agent_id="support",
                        )
                    ],
                ),
                entity_filter=IntelligentFieldValueEntityFilter(
                    entity_ids=[
                        EntityId(
                            reference_id="conv-123",
                            app_id="zendesk",
                            type="CONVERSATION",
                            organization_id="acme",
                            agent_id="support",
                        )
                    ],
                ),
                page=0,
                size=20,
                sort="CREATED_AT",
                sort_desc=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_values(
            field_filter=field_filter,
            entity_filter=entity_filter,
            created_after=created_after,
            created_before=created_before,
            include_unknown_values=include_unknown_values,
            sort=sort,
            variant_id=variant_id,
            page=page,
            size=size,
            sort_desc=sort_desc,
            request_options=request_options,
        )
        return _response.data
