# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..commons.errors.bad_request_error import BadRequestError
from ..commons.errors.not_found_error import NotFoundError
from ..commons.errors.payload_too_large_error import PayloadTooLargeError
from ..commons.errors.server_error import ServerError
from ..commons.errors.too_many_requests_error import TooManyRequestsError
from ..commons.types.capability_status import CapabilityStatus
from ..commons.types.entity_id_base import EntityIdBase
from ..commons.types.entity_id_without_agent import EntityIdWithoutAgent
from ..commons.types.entity_type import EntityType
from ..commons.types.error_message import ErrorMessage
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from .types.enum_option import EnumOption
from .types.intelligent_field_detail_response import IntelligentFieldDetailResponse
from .types.intelligent_field_response import IntelligentFieldResponse
from .types.intelligent_field_type import IntelligentFieldType
from .types.intelligent_field_value_entity_filter import IntelligentFieldValueEntityFilter
from .types.intelligent_field_value_field_filter import IntelligentFieldValueFieldFilter
from .types.intelligent_field_value_search_response import IntelligentFieldValueSearchResponse
from .types.intelligent_field_value_sort_field import IntelligentFieldValueSortField

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawIntelligentFieldsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_or_update(
        self,
        *,
        name: str,
        field_id: EntityIdBase,
        entity_type: EntityType,
        validation_type: IntelligentFieldType,
        definition: str,
        description: typing.Optional[str] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IntelligentFieldResponse]:
        """
        Create a new intelligent field, or replace it if one already exists with the same
        `fieldId.referenceId`. Intelligent fields hold LLM-generated values computed for
        entities such as conversations.

        New fields are created with `status: INACTIVE` and are not evaluated until activated
        with the patch endpoint. A new field created in a `variantId` starts `ACTIVE` instead,
        since it is evaluated only once that variant is published and given traffic; it starts
        `INACTIVE` while the agent is at its limit of active fields. `definition` is limited
        to 5,000 characters.

        A replace that names a `variantId` must keep the field's `validationType` as that
        variant has it, or it is rejected with reason `INTELLIGENT_FIELD_TYPE_CHANGED`. To use
        a different type, create a new field. A field deleted in the variant may be recreated
        with any type.

        Parameters
        ----------
        name : str
            Display name for the intelligent field

        field_id : EntityIdBase
            ID that uniquely identifies this intelligent field. `referenceId` is supplied by the
            caller and is how the field is addressed on every other endpoint.

        entity_type : EntityType
            Target entity type for evaluation. CONVERSATION is supported, and AGENT_USER is supported for agents with user-level intelligent fields enabled. The backend will return an error for other types.

        validation_type : IntelligentFieldType
            The type of value this field holds. It constrains the schema the LLM is asked to fill
            and the JSON type of the computed `value`.

            - STRING / MULTILINE: a single string
            - MULTI_SELECT: a list of strings
            - BOOLEAN: `true` or `false`
            - NUMBER: a number

            For a single select, use STRING or NUMBER together with `enumOptions`.

        definition : str
            Definition used by the LLM when generating this field's value

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            On a request, the agent variant to stage the write in. On a response, the variant the request named, if any; absent when it named none.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            The finite set of values this field may take. Omit to let the LLM produce any value of
            the `validationType`. Options may be added later with the patch endpoint, but not removed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IntelligentFieldResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/intelligent-fields",
            method="PUT",
            json={
                "name": name,
                "description": description,
                "fieldId": convert_and_respect_annotation_metadata(
                    object_=field_id, annotation=EntityIdBase, direction="write"
                ),
                "entityType": entity_type,
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "validationType": validation_type,
                "definition": definition,
                "enumOptions": convert_and_respect_annotation_metadata(
                    object_=enum_options, annotation=typing.Sequence[EnumOption], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IntelligentFieldDetailResponse]:
        """
        Deprecated. Use `GET /v1/capabilities/INTELLIGENT_FIELD/{referenceId}`, which reads any
        kind of capability the same way. It does not carry `referencingCharters`; search
        charters to find the ones that reference a capability.

        Get an intelligent field by its supplied ID

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to get. All other entity ID fields are inferred from the request.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to get. If not provided the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant reference ID to resolve the intelligent field's version through. Required on an agent with versioned intelligent fields; a request that omits it there is rejected with reason `VARIANT_REQUIRED`. Otherwise, if omitted, the agent's only variant is used.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IntelligentFieldDetailResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="GET",
            params={
                "appId": app_id,
                "variantReferenceId": variant_reference_id,
                "variantAppId": variant_app_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldDetailResponse,
                    parse_obj_as(
                        type_=IntelligentFieldDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def patch(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = OMIT,
        definition: typing.Optional[str] = OMIT,
        status: typing.Optional[CapabilityStatus] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        variant_app_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IntelligentFieldResponse]:
        """
        Update the mutable properties of an intelligent field. Only the properties present in
        the request body are changed.

        This is also how a field is activated and deactivated: set `status` to `ACTIVE` to
        start evaluating it, or `INACTIVE` to stop. `name`, `entityType`, and `validationType`
        cannot be changed after creation.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to patch.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to update. If not provided the ID of the calling app will be used.

        definition : typing.Optional[str]
            The definition of the intelligent field. This text will be influential in guiding the LLM to produce the desired results. Limited to 5,000 characters.

        status : typing.Optional[CapabilityStatus]
            The lifecycle state for whether this field is evaluated. Use ACTIVE to start
            evaluating the field and INACTIVE to stop.

            Each agent has a limit on how many fields may be ACTIVE at once; activating a
            field beyond that limit is rejected. A field referenced by an active precondition
            cannot be deactivated.

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Updated enum options for fields that constrain the LLM to a finite set. Omit to leave unchanged. The new list must be a superset of the existing options (add-only; removals are rejected).

        variant_id : typing.Optional[EntityIdWithoutAgent]
            The agent variant to stage this patch in. Required on an agent with versioned intelligent fields; a patch that omits it there is rejected with reason `VARIANT_REQUIRED`.

        variant_app_id : typing.Optional[str]
            Deprecated, use `variantId.appId`, which wins when both are set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IntelligentFieldResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="PATCH",
            json={
                "appId": app_id,
                "definition": definition,
                "status": status,
                "description": description,
                "enumOptions": convert_and_respect_annotation_metadata(
                    object_=enum_options, annotation=typing.Sequence[EnumOption], direction="write"
                ),
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "variantAppId": variant_app_id,
            },
            headers={
                "content-type": "application/merge-patch+json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IntelligentFieldResponse]:
        """
        Deprecated. Use `DELETE /v1/capabilities/INTELLIGENT_FIELD/{referenceId}`, which
        deletes any kind of capability the same way. That endpoint returns no body.

        Soft delete an intelligent field. Only INACTIVE fields can be deleted.

        Deleted fields are excluded from search results but can still be retrieved by ID.
        Creating a new field with the same referenceId as a deleted field will overwrite
        the deleted field and restore it with the status a new field gets.

        Deleted fields cannot be modified.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to delete.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant to stage the delete in, by reference ID. Required on an agent with versioned intelligent fields; a delete that omits it there is rejected with reason `VARIANT_REQUIRED`.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IntelligentFieldResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="DELETE",
            params={
                "appId": app_id,
                "variantReferenceId": variant_reference_id,
                "variantAppId": variant_app_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search_values(
        self,
        *,
        field_filter: typing.Optional[IntelligentFieldValueFieldFilter] = OMIT,
        entity_filter: typing.Optional[IntelligentFieldValueEntityFilter] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        created_before: typing.Optional[dt.datetime] = OMIT,
        include_unknown_values: typing.Optional[bool] = OMIT,
        sort: typing.Optional[IntelligentFieldValueSortField] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        page: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        sort_desc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IntelligentFieldValueSearchResponse]:
        """
        Search the values that have been computed for intelligent fields, across entities.
        Supports filtering by properties of the field, by target entity, and by when the
        value was computed.

        Values only exist for fields that were ACTIVE when the entity was evaluated, so a
        newly activated field returns nothing until evaluation has run.

        Parameters
        ----------
        field_filter : typing.Optional[IntelligentFieldValueFieldFilter]
            Filter by properties of the intelligent field definition. If not provided, returns values for all fields.

        entity_filter : typing.Optional[IntelligentFieldValueEntityFilter]
            Filter by properties of the target entity. If not provided, returns values across all entities.

        created_after : typing.Optional[dt.datetime]
            Filter values computed on or after this timestamp

        created_before : typing.Optional[dt.datetime]
            Filter values computed on or before this timestamp

        include_unknown_values : typing.Optional[bool]
            Whether to include results where the LLM could not determine a value (value is null). Defaults to false.

        sort : typing.Optional[IntelligentFieldValueSortField]
            Field to sort by. Defaults to CREATED_AT.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            Returns values of the fields in this agent variant's scope: its published snapshot plus
            its staged edits, matched by field. A value is included whichever variant's conversation
            produced it, and is named as this variant names the field. If not provided, returns
            values from all variants.

            To see values from the conversations pinned to a variant, filter conversations by
            `variantIds` in conversation search or the analytics APIs.

        page : typing.Optional[int]
            Page number to return, defaults to 0

        size : typing.Optional[int]
            The size of the page to return, defaults to 20. Max 1000.

        sort_desc : typing.Optional[bool]
            Whether to sort descending, defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IntelligentFieldValueSearchResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/intelligent-fields/values/search",
            method="POST",
            json={
                "fieldFilter": convert_and_respect_annotation_metadata(
                    object_=field_filter, annotation=IntelligentFieldValueFieldFilter, direction="write"
                ),
                "entityFilter": convert_and_respect_annotation_metadata(
                    object_=entity_filter, annotation=IntelligentFieldValueEntityFilter, direction="write"
                ),
                "createdAfter": created_after,
                "createdBefore": created_before,
                "includeUnknownValues": include_unknown_values,
                "sort": sort,
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "page": page,
                "size": size,
                "sortDesc": sort_desc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldValueSearchResponse,
                    parse_obj_as(
                        type_=IntelligentFieldValueSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawIntelligentFieldsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_or_update(
        self,
        *,
        name: str,
        field_id: EntityIdBase,
        entity_type: EntityType,
        validation_type: IntelligentFieldType,
        definition: str,
        description: typing.Optional[str] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IntelligentFieldResponse]:
        """
        Create a new intelligent field, or replace it if one already exists with the same
        `fieldId.referenceId`. Intelligent fields hold LLM-generated values computed for
        entities such as conversations.

        New fields are created with `status: INACTIVE` and are not evaluated until activated
        with the patch endpoint. A new field created in a `variantId` starts `ACTIVE` instead,
        since it is evaluated only once that variant is published and given traffic; it starts
        `INACTIVE` while the agent is at its limit of active fields. `definition` is limited
        to 5,000 characters.

        A replace that names a `variantId` must keep the field's `validationType` as that
        variant has it, or it is rejected with reason `INTELLIGENT_FIELD_TYPE_CHANGED`. To use
        a different type, create a new field. A field deleted in the variant may be recreated
        with any type.

        Parameters
        ----------
        name : str
            Display name for the intelligent field

        field_id : EntityIdBase
            ID that uniquely identifies this intelligent field. `referenceId` is supplied by the
            caller and is how the field is addressed on every other endpoint.

        entity_type : EntityType
            Target entity type for evaluation. CONVERSATION is supported, and AGENT_USER is supported for agents with user-level intelligent fields enabled. The backend will return an error for other types.

        validation_type : IntelligentFieldType
            The type of value this field holds. It constrains the schema the LLM is asked to fill
            and the JSON type of the computed `value`.

            - STRING / MULTILINE: a single string
            - MULTI_SELECT: a list of strings
            - BOOLEAN: `true` or `false`
            - NUMBER: a number

            For a single select, use STRING or NUMBER together with `enumOptions`.

        definition : str
            Definition used by the LLM when generating this field's value

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            On a request, the agent variant to stage the write in. On a response, the variant the request named, if any; absent when it named none.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            The finite set of values this field may take. Omit to let the LLM produce any value of
            the `validationType`. Options may be added later with the patch endpoint, but not removed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IntelligentFieldResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/intelligent-fields",
            method="PUT",
            json={
                "name": name,
                "description": description,
                "fieldId": convert_and_respect_annotation_metadata(
                    object_=field_id, annotation=EntityIdBase, direction="write"
                ),
                "entityType": entity_type,
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "validationType": validation_type,
                "definition": definition,
                "enumOptions": convert_and_respect_annotation_metadata(
                    object_=enum_options, annotation=typing.Sequence[EnumOption], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IntelligentFieldDetailResponse]:
        """
        Deprecated. Use `GET /v1/capabilities/INTELLIGENT_FIELD/{referenceId}`, which reads any
        kind of capability the same way. It does not carry `referencingCharters`; search
        charters to find the ones that reference a capability.

        Get an intelligent field by its supplied ID

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to get. All other entity ID fields are inferred from the request.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to get. If not provided the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant reference ID to resolve the intelligent field's version through. Required on an agent with versioned intelligent fields; a request that omits it there is rejected with reason `VARIANT_REQUIRED`. Otherwise, if omitted, the agent's only variant is used.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IntelligentFieldDetailResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="GET",
            params={
                "appId": app_id,
                "variantReferenceId": variant_reference_id,
                "variantAppId": variant_app_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldDetailResponse,
                    parse_obj_as(
                        type_=IntelligentFieldDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def patch(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = OMIT,
        definition: typing.Optional[str] = OMIT,
        status: typing.Optional[CapabilityStatus] = OMIT,
        description: typing.Optional[str] = OMIT,
        enum_options: typing.Optional[typing.Sequence[EnumOption]] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        variant_app_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IntelligentFieldResponse]:
        """
        Update the mutable properties of an intelligent field. Only the properties present in
        the request body are changed.

        This is also how a field is activated and deactivated: set `status` to `ACTIVE` to
        start evaluating it, or `INACTIVE` to stop. `name`, `entityType`, and `validationType`
        cannot be changed after creation.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to patch.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to update. If not provided the ID of the calling app will be used.

        definition : typing.Optional[str]
            The definition of the intelligent field. This text will be influential in guiding the LLM to produce the desired results. Limited to 5,000 characters.

        status : typing.Optional[CapabilityStatus]
            The lifecycle state for whether this field is evaluated. Use ACTIVE to start
            evaluating the field and INACTIVE to stop.

            Each agent has a limit on how many fields may be ACTIVE at once; activating a
            field beyond that limit is rejected. A field referenced by an active precondition
            cannot be deactivated.

        description : typing.Optional[str]
            A plain text description of the intelligent field.

        enum_options : typing.Optional[typing.Sequence[EnumOption]]
            Updated enum options for fields that constrain the LLM to a finite set. Omit to leave unchanged. The new list must be a superset of the existing options (add-only; removals are rejected).

        variant_id : typing.Optional[EntityIdWithoutAgent]
            The agent variant to stage this patch in. Required on an agent with versioned intelligent fields; a patch that omits it there is rejected with reason `VARIANT_REQUIRED`.

        variant_app_id : typing.Optional[str]
            Deprecated, use `variantId.appId`, which wins when both are set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IntelligentFieldResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="PATCH",
            json={
                "appId": app_id,
                "definition": definition,
                "status": status,
                "description": description,
                "enumOptions": convert_and_respect_annotation_metadata(
                    object_=enum_options, annotation=typing.Sequence[EnumOption], direction="write"
                ),
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "variantAppId": variant_app_id,
            },
            headers={
                "content-type": "application/merge-patch+json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self,
        field_reference_id: str,
        *,
        app_id: typing.Optional[str] = None,
        variant_reference_id: typing.Optional[str] = None,
        variant_app_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IntelligentFieldResponse]:
        """
        Deprecated. Use `DELETE /v1/capabilities/INTELLIGENT_FIELD/{referenceId}`, which
        deletes any kind of capability the same way. That endpoint returns no body.

        Soft delete an intelligent field. Only INACTIVE fields can be deleted.

        Deleted fields are excluded from search results but can still be retrieved by ID.
        Creating a new field with the same referenceId as a deleted field will overwrite
        the deleted field and restore it with the status a new field gets.

        Deleted fields cannot be modified.

        Parameters
        ----------
        field_reference_id : str
            The reference ID of the intelligent field to delete.

        app_id : typing.Optional[str]
            The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.

        variant_reference_id : typing.Optional[str]
            The agent variant to stage the delete in, by reference ID. Required on an agent with versioned intelligent fields; a delete that omits it there is rejected with reason `VARIANT_REQUIRED`.

        variant_app_id : typing.Optional[str]
            The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IntelligentFieldResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/intelligent-fields/{jsonable_encoder(field_reference_id)}",
            method="DELETE",
            params={
                "appId": app_id,
                "variantReferenceId": variant_reference_id,
                "variantAppId": variant_app_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldResponse,
                    parse_obj_as(
                        type_=IntelligentFieldResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search_values(
        self,
        *,
        field_filter: typing.Optional[IntelligentFieldValueFieldFilter] = OMIT,
        entity_filter: typing.Optional[IntelligentFieldValueEntityFilter] = OMIT,
        created_after: typing.Optional[dt.datetime] = OMIT,
        created_before: typing.Optional[dt.datetime] = OMIT,
        include_unknown_values: typing.Optional[bool] = OMIT,
        sort: typing.Optional[IntelligentFieldValueSortField] = OMIT,
        variant_id: typing.Optional[EntityIdWithoutAgent] = OMIT,
        page: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        sort_desc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IntelligentFieldValueSearchResponse]:
        """
        Search the values that have been computed for intelligent fields, across entities.
        Supports filtering by properties of the field, by target entity, and by when the
        value was computed.

        Values only exist for fields that were ACTIVE when the entity was evaluated, so a
        newly activated field returns nothing until evaluation has run.

        Parameters
        ----------
        field_filter : typing.Optional[IntelligentFieldValueFieldFilter]
            Filter by properties of the intelligent field definition. If not provided, returns values for all fields.

        entity_filter : typing.Optional[IntelligentFieldValueEntityFilter]
            Filter by properties of the target entity. If not provided, returns values across all entities.

        created_after : typing.Optional[dt.datetime]
            Filter values computed on or after this timestamp

        created_before : typing.Optional[dt.datetime]
            Filter values computed on or before this timestamp

        include_unknown_values : typing.Optional[bool]
            Whether to include results where the LLM could not determine a value (value is null). Defaults to false.

        sort : typing.Optional[IntelligentFieldValueSortField]
            Field to sort by. Defaults to CREATED_AT.

        variant_id : typing.Optional[EntityIdWithoutAgent]
            Returns values of the fields in this agent variant's scope: its published snapshot plus
            its staged edits, matched by field. A value is included whichever variant's conversation
            produced it, and is named as this variant names the field. If not provided, returns
            values from all variants.

            To see values from the conversations pinned to a variant, filter conversations by
            `variantIds` in conversation search or the analytics APIs.

        page : typing.Optional[int]
            Page number to return, defaults to 0

        size : typing.Optional[int]
            The size of the page to return, defaults to 20. Max 1000.

        sort_desc : typing.Optional[bool]
            Whether to sort descending, defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IntelligentFieldValueSearchResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/intelligent-fields/values/search",
            method="POST",
            json={
                "fieldFilter": convert_and_respect_annotation_metadata(
                    object_=field_filter, annotation=IntelligentFieldValueFieldFilter, direction="write"
                ),
                "entityFilter": convert_and_respect_annotation_metadata(
                    object_=entity_filter, annotation=IntelligentFieldValueEntityFilter, direction="write"
                ),
                "createdAfter": created_after,
                "createdBefore": created_before,
                "includeUnknownValues": include_unknown_values,
                "sort": sort,
                "variantId": convert_and_respect_annotation_metadata(
                    object_=variant_id, annotation=EntityIdWithoutAgent, direction="write"
                ),
                "page": page,
                "size": size,
                "sortDesc": sort_desc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IntelligentFieldValueSearchResponse,
                    parse_obj_as(
                        type_=IntelligentFieldValueSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
