# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...commons.types.event_trigger_type import EventTriggerType
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs


class EventTriggerBase(UniversalBaseModel):
    type: EventTriggerType = pydantic.Field()
    """
    The type of event trigger this app wishes to handle.
    
    Conversation triggers fire when a conversation is created, after each additional message, and upon deletion events.
    There is a small delay before trigger execution to allow time for conversation analysis to complete.
    
    Events are immutable, so an event trigger fires immediately after the event is created.
    
    Inbox triggers fire when an inbox item is created or updated.
    """

    condition: typing.Optional["EventCondition"] = pydantic.Field(default=None)
    """
    Narrows which events fire this trigger. Without one the trigger fires for every event on
    the agent. Re-registering writes whatever condition the request carries, so omitting it
    removes one; PATCH changes or removes a condition without re-registering.
    
    Only allowed on `EVENT_CREATED`; the other trigger types reject it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.event_condition_group import EventConditionGroup  # noqa: E402, F401, I001
from ...commons.types.event_condition import EventCondition  # noqa: E402, F401, I001

update_forward_refs(EventTriggerBase)
