# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ...core.serialization import FieldMetadata
from .charter_base import CharterBase
from .charter_children_exclusion_policy import CharterChildrenExclusionPolicy
from .charter_references import CharterReferences
from .charter_status import CharterStatus
from .charter_type import CharterType


class CharterResponse(CharterBase):
    """
    Examples
    --------
    import datetime

    from mavenagi.charters import CharterReferences, CharterResponse
    from mavenagi.commons import (
        ConversationPreconditionResponse_Tags,
        EntityId,
        PreconditionResponse_Conversation,
    )

    CharterResponse(
        charter_id=EntityId(
            reference_id="cancellation-flow",
            app_id="support-app",
            organization_id="acme",
            agent_id="support",
            type="CHARTER",
        ),
        name="Cancellation Flow",
        manual="Guide the user through the cancellation process with empathy. Always confirm their intent before proceeding.",
        child_charter_ids=[],
        references=CharterReferences(
            knowledge_bases=[],
            action_ids=[],
        ),
        precondition=PreconditionResponse_Conversation(
            value=ConversationPreconditionResponse_Tags(
                tags={"cancellation"},
            )
        ),
        status="ACTIVE",
        type="STANDARD",
        user_rank=0,
        created_at=datetime.datetime.fromisoformat(
            "2025-01-01 00:00:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2025-01-15 12:30:00+00:00",
        ),
    )
    """

    charter_id: typing_extensions.Annotated[EntityId, FieldMetadata(alias="charterId")] = pydantic.Field()
    """
    ID that uniquely identifies this charter.
    """

    parent_charter_id: typing_extensions.Annotated[
        typing.Optional[EntityId], FieldMetadata(alias="parentCharterId")
    ] = pydantic.Field(default=None)
    """
    The ID of the parent charter. Empty for root-level charters.
    
    Charter hierarchies are acyclic, so following this field repeatedly always reaches a
    root-level charter in a finite number of steps. A charter is never its own ancestor, and
    callers walking the chain do not need their own cycle guard.
    """

    child_charter_ids: typing_extensions.Annotated[typing.List[EntityId], FieldMetadata(alias="childCharterIds")] = (
        pydantic.Field()
    )
    """
    The IDs of direct child charters, in their userRank order.
    """

    precondition: typing.Optional["PreconditionResponse"] = pydantic.Field(default=None)
    """
    The rule controlling when this charter applies. Empty means wildcard (always matches).
    """

    status: CharterStatus = pydantic.Field()
    """
    The lifecycle status of this charter.
    """

    type: typing.Optional[CharterType] = pydantic.Field(default=None)
    """
    The behavioral mode for this charter. Defaults to STANDARD.
    """

    children_exclusion_policy: typing_extensions.Annotated[
        typing.Optional[CharterChildrenExclusionPolicy], FieldMetadata(alias="childrenExclusionPolicy")
    ] = pydantic.Field(default=None)
    """
    Whether this charter's children mutually exclude each other. Defaults to DEFAULT.
    """

    user_rank: typing_extensions.Annotated[int, FieldMetadata(alias="userRank")] = pydantic.Field()
    """
    User-defined rank among siblings. Lower rank = higher priority. When multiple charters
    in the same leaf group match, the lowest-rank ACTIVE charter is applied.
    Auto-assigned as `max(siblings.userRank) + 1` (0 if no siblings) when not explicitly set.
    """

    references: CharterReferences = pydantic.Field()
    """
    Context items (knowledge bases and actions) this charter makes available.
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    The date and time this charter was created.
    """

    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field()
    """
    The date and time this charter was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.precondition_group_response import PreconditionGroupResponse  # noqa: E402, F401, I001
from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001
from ...commons.types.precondition_response import PreconditionResponse  # noqa: E402, F401, I001

update_forward_refs(CharterResponse)
