# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata
from ...segments.types.segment_summary import SegmentSummary
from .charter_children_exclusion_policy import CharterChildrenExclusionPolicy
from .charter_status import CharterStatus
from .charter_type import CharterType


class CharterSummary(UniversalBaseModel):
    """
    A lightweight charter representation for search results and ancestor paths.
    Use the get endpoint to retrieve the full charter with references, manual, and children.
    """

    charter_id: typing_extensions.Annotated[EntityId, FieldMetadata(alias="charterId")] = pydantic.Field()
    """
    ID that uniquely identifies this charter.
    """

    name: str = pydantic.Field()
    """
    The display name of the charter.
    """

    segment_summary: typing_extensions.Annotated[
        typing.Optional[SegmentSummary], FieldMetadata(alias="segmentSummary")
    ] = pydantic.Field(default=None)
    """
    The segment backing this charter's rule. An implementation detail of `precondition`;
    read that instead.
    """

    precondition: typing.Optional["PreconditionResponse"] = pydantic.Field(default=None)
    """
    The rule controlling when this charter applies, read from the charter's backing
    segment. Null means wildcard (always matches).
    """

    parent_charter_id: typing_extensions.Annotated[
        typing.Optional[EntityId], FieldMetadata(alias="parentCharterId")
    ] = pydantic.Field(default=None)
    """
    The ID of the parent charter. Null for root-level charters.
    """

    status: CharterStatus = pydantic.Field()
    """
    The lifecycle status of this charter.
    """

    type: typing.Optional[CharterType] = pydantic.Field(default=None)
    """
    The behavioral mode for this charter. Defaults to STANDARD.
    """

    children_exclusion_policy: typing_extensions.Annotated[
        typing.Optional[CharterChildrenExclusionPolicy], FieldMetadata(alias="childrenExclusionPolicy")
    ] = pydantic.Field(default=None)
    """
    Whether this charter's children mutually exclude each other. Defaults to DEFAULT.
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    The date and time this charter was created.
    """

    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field()
    """
    The date and time this charter was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.precondition_group_response import PreconditionGroupResponse  # noqa: E402, F401, I001
from ...commons.types.precondition_response import PreconditionResponse  # noqa: E402, F401, I001

update_forward_refs(CharterSummary)
