# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata


class CharterKnowledgeBaseReference(UniversalBaseModel):
    """
    A knowledge base a charter makes available, and optionally which of its documents.
    """

    knowledge_base_id: typing_extensions.Annotated[EntityId, FieldMetadata(alias="knowledgeBaseId")] = pydantic.Field()
    """
    The knowledge base this charter makes available.
    """

    document_filter: typing_extensions.Annotated[
        typing.Optional["MetadataFilter"], FieldMetadata(alias="documentFilter")
    ] = pydantic.Field(default=None)
    """
    Narrows this reference to the documents in the knowledge base whose `metadata`
    satisfies this filter. Omit to reference every document in the knowledge base.
    
    An entry's `key` is a metadata key on the document. A document carrying no such
    key matches only `presence` `IS_UNDETERMINED`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001
from ...commons.types.metadata_filter import MetadataFilter  # noqa: E402, F401, I001

update_forward_refs(CharterKnowledgeBaseReference)
