# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id_base import EntityIdBase
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .charter_content import CharterContent


class CharterRequest(CharterContent):
    """
    Examples
    --------
    from mavenagi.charters import CharterReferences, CharterRequest
    from mavenagi.commons import (
        ConversationPrecondition_Tags,
        EntityIdBase,
        Precondition_Conversation,
    )

    CharterRequest(
        charter_id=EntityIdBase(
            reference_id="cancellation-flow",
        ),
        name="Cancellation Flow",
        manual="Guide the user through the cancellation process with empathy. Always confirm their intent before proceeding.",
        precondition=Precondition_Conversation(
            value=ConversationPrecondition_Tags(
                tags={"cancellation"},
            )
        ),
        status="ACTIVE",
        type="STANDARD",
        references=CharterReferences(
            knowledge_bases=[],
            action_ids=[],
        ),
    )
    """

    charter_id: typing_extensions.Annotated[EntityIdBase, FieldMetadata(alias="charterId")] = pydantic.Field()
    """
    ID that uniquely identifies this charter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001
from ...commons.types.precondition_group import PreconditionGroup  # noqa: E402, F401, I001
