# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .charter_response import CharterResponse


class CharterAncestorsResponse(UniversalBaseModel):
    charters: typing.List[CharterResponse] = pydantic.Field()
    """
    The requested charter and all of its ancestors up to the root,
    ordered from root to leaf. The last element is the requested charter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001
from ...commons.types.precondition_group_response import PreconditionGroupResponse  # noqa: E402, F401, I001

update_forward_refs(CharterAncestorsResponse)
