# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.base_capped_paginated_request import BaseCappedPaginatedRequest
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata


class CharterListChildrenRequest(BaseCappedPaginatedRequest):
    """
    Note: sortDesc is ignored — results are always ordered by userRank ASC,
    updatedAt DESC within each group.

    Examples
    --------
    from mavenagi.charters import CharterListChildrenRequest

    CharterListChildrenRequest(
        parent_ids=[],
    )
    """

    parent_ids: typing_extensions.Annotated[typing.List[EntityId], FieldMetadata(alias="parentIds")] = pydantic.Field()
    """
    Parents whose direct children to return. Pass an empty list to fetch root
    charters for the agent. Roots and specific parents cannot be mixed in one request.
    Maximum 50 parent IDs per request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
