# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ...core.serialization import FieldMetadata
from .charter_base import CharterBase
from .charter_references import CharterReferences
from .charter_status import CharterStatus
from .charter_type import CharterType


class CharterContent(CharterBase):
    """
    A charter's full content: its text fields, its position in the tree, the rule controlling
    when it applies, its lifecycle status and its references.

    `parentCharterId` is `nullable`, not `optional`: null is meaningful -- root level -- and
    distinct from absent.
    """

    parent_charter_id: typing_extensions.Annotated[
        typing.Optional[EntityId], FieldMetadata(alias="parentCharterId")
    ] = pydantic.Field(default=None)
    """
    The fully-qualified ID of the parent charter. Send null to place this charter at the
    root level -- the field is nullable rather than optional, so null is meaningful and
    distinct from absent.
    
    The resulting tree must remain acyclic. A write that would make this charter its own
    ancestor is rejected with a 400 and leaves the tree unchanged.
    """

    precondition: typing.Optional["Precondition"] = pydantic.Field(default=None)
    """
    The rule controlling when this charter applies. Preconditions on
    ancestor charters are AND'd together with this charter's own
    precondition to determine whether there is a match. When null, the
    charter is a wildcard and always matches (subject to ancestor
    preconditions still combining with AND logic).
    """

    status: CharterStatus = pydantic.Field()
    """
    Desired lifecycle status.
    """

    type: typing.Optional[CharterType] = pydantic.Field(default=None)
    """
    The behavioral mode for this charter. Defaults to STANDARD when omitted.
    
    Set at creation and immutable afterward. When updating an existing charter (via
    createOrUpdate), this field must either be omitted or repeat the charter's current
    type — a differing value is rejected. There is no way to change a charter's type once
    created. (Recreating a deleted charter is a create, so it may pick any type.)
    
    STRICT_RETURN charters cannot have children, and reference neither knowledge bases nor
    actions: no charter may name a STRICT_RETURN charter as its parent.
    """

    user_rank: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="userRank")] = pydantic.Field(
        default=None
    )
    """
    User-defined 0-indexed rank among siblings.
    
    The rank is currently only meaningful for leaf charters as we enforce
    mutual exclusion among the leafs and pick only the highest ranked
    (lowest numerical value) leaf to include in the round. userRank may have
    gaps.
    
    Lower rank = higher priority. When provided and conflicts with an
    existing sibling, siblings at that rank and above are shifted up by 1
    (like linked list semantics). When omitted on create, auto-assigned as
    `max(siblings.userRank) + 1` (0 if no siblings).
    """

    references: CharterReferences = pydantic.Field()
    """
    Context items (knowledge bases and actions) this charter makes available.
    Maximum 50 knowledge bases and 50 actions per charter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.precondition_group import PreconditionGroup  # noqa: E402, F401, I001
from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001
from ...commons.types.precondition import Precondition  # noqa: E402, F401, I001

update_forward_refs(CharterContent)
