# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata
from .charter_knowledge_base_reference import CharterKnowledgeBaseReference


class CharterReferences(UniversalBaseModel):
    """
    Context items (knowledge bases and actions) a charter makes available.
    """

    knowledge_bases: typing_extensions.Annotated[
        typing.Optional[typing.List[CharterKnowledgeBaseReference]], FieldMetadata(alias="knowledgeBases")
    ] = pydantic.Field(default=None)
    """
    The knowledge bases this charter makes available, each optionally narrowed to a
    subset of that knowledge base's documents.
    
    At most one entry per knowledge base. Maximum 50 knowledge bases per charter.
    
    On a write, supplying this replaces the charter's whole knowledge base set. A response
    always populates it.
    """

    action_ids: typing_extensions.Annotated[typing.List[EntityId], FieldMetadata(alias="actionIds")] = pydantic.Field()
    """
    The IDs of actions this charter makes available.
    Maximum 50 actions per charter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.metadata_filter_group import MetadataFilterGroup  # noqa: E402, F401, I001

update_forward_refs(CharterReferences)
