# This file was auto-generated by Fern from our API Definition.

import typing

KnowledgeBaseIndexingStatus = typing.Union[
    typing.Literal["BUILDING", "INDEXING", "INDEXED", "PUBLISHED", "FAILED", "SUPERSEDED"], typing.Any
]
