# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .knowledge_base_indexing_status import KnowledgeBaseIndexingStatus


class KnowledgeBaseIndexingProgressState(UniversalBaseModel):
    version_id: typing_extensions.Annotated[EntityId, FieldMetadata(alias="versionId")] = pydantic.Field()
    """
    The unique ID of a knowledge base version.
    """

    status: KnowledgeBaseIndexingStatus = pydantic.Field()
    """
    The status of the knowledge base indexing process.
    """

    expected_count: typing_extensions.Annotated[int, FieldMetadata(alias="expectedCount")] = pydantic.Field()
    """
    The expected number of documents to be indexed for the latest knowledge base version.
    """

    indexed_count: typing_extensions.Annotated[int, FieldMetadata(alias="indexedCount")] = pydantic.Field()
    """
    The number of documents that have been indexed so far for the latest knowledge base version.
    """

    failed_count: typing_extensions.Annotated[int, FieldMetadata(alias="failedCount")] = pydantic.Field()
    """
    The number of documents that have failed to index for the latest knowledge base version.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
