# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..commons.errors.bad_request_error import BadRequestError
from ..commons.errors.not_found_error import NotFoundError
from ..commons.errors.payload_too_large_error import PayloadTooLargeError
from ..commons.errors.server_error import ServerError
from ..commons.errors.too_many_requests_error import TooManyRequestsError
from ..commons.types.entity_id_base import EntityIdBase
from ..commons.types.error_message import ErrorMessage
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from .types.conversation_kickoff import ConversationKickoff

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawConversationKickoffsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_or_update(
        self,
        *,
        kickoff_id: EntityIdBase,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ConversationKickoff]:
        """
        Register or update one of the calling app's Conversation Kickoffs for this agent. An app may
        hold multiple independent installs, and any number of an agent's kickoffs may run at once.

        A newly installed kickoff starts inactive, so installing one never changes an agent's
        behaviour on its own. Updating an existing one rewrites its name and description and leaves
        its status alone, so re-registering on every install refresh never deactivates a kickoff
        that is already live. Use the capability APIs to activate it, and to read, search or delete
        it afterwards.

        Parameters
        ----------
        kickoff_id : EntityIdBase
            ID that uniquely identifies this Conversation Kickoff. Must be unique within the
            calling app.

        name : str
            The kickoff's display name, shown to whoever manages the agent.

        description : typing.Optional[str]
            What the kickoff does, shown to whoever manages the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ConversationKickoff]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/conversation-kickoffs",
            method="PUT",
            json={
                "kickoffId": convert_and_respect_annotation_metadata(
                    object_=kickoff_id, annotation=EntityIdBase, direction="write"
                ),
                "name": name,
                "description": description,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConversationKickoff,
                    parse_obj_as(
                        type_=ConversationKickoff,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawConversationKickoffsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_or_update(
        self,
        *,
        kickoff_id: EntityIdBase,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ConversationKickoff]:
        """
        Register or update one of the calling app's Conversation Kickoffs for this agent. An app may
        hold multiple independent installs, and any number of an agent's kickoffs may run at once.

        A newly installed kickoff starts inactive, so installing one never changes an agent's
        behaviour on its own. Updating an existing one rewrites its name and description and leaves
        its status alone, so re-registering on every install refresh never deactivates a kickoff
        that is already live. Use the capability APIs to activate it, and to read, search or delete
        it afterwards.

        Parameters
        ----------
        kickoff_id : EntityIdBase
            ID that uniquely identifies this Conversation Kickoff. Must be unique within the
            calling app.

        name : str
            The kickoff's display name, shown to whoever manages the agent.

        description : typing.Optional[str]
            What the kickoff does, shown to whoever manages the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ConversationKickoff]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/conversation-kickoffs",
            method="PUT",
            json={
                "kickoffId": convert_and_respect_annotation_metadata(
                    object_=kickoff_id, annotation=EntityIdBase, direction="write"
                ),
                "name": name,
                "description": description,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConversationKickoff,
                    parse_obj_as(
                        type_=ConversationKickoff,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 413:
                raise PayloadTooLargeError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise ServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorMessage,
                        parse_obj_as(
                            type_=ErrorMessage,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
