# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id_base import EntityIdBase
from ...commons.types.inbox_item_severity import InboxItemSeverity
from ...commons.types.inbox_item_status import InboxItemStatus
from ...commons.types.scoped_entity import ScopedEntity
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class InboxItemCreateRequest(UniversalBaseModel):
    """
    Examples
    --------
    from mavenagi.commons import EntityId, EntityIdBase, ScopedEntity
    from mavenagi.inbox import InboxItemCreateRequest

    InboxItemCreateRequest(
        inbox_item_id=EntityIdBase(
            reference_id="todo-item-1",
        ),
        status="OPEN",
        severity="HIGH",
        title="Todo Item",
        description="This is the first todo item.",
        metadata={"key": "value"},
        external_url="todo.com",
        references=[
            ScopedEntity(
                entity_id=EntityId(
                    type="CONVERSATION_MESSAGE",
                    app_id="app1",
                    reference_id="msgRef1201",
                    organization_id="acme",
                    agent_id="support",
                ),
                scope_entity_id=EntityId(
                    type="CONVERSATION",
                    app_id="app1",
                    reference_id="ref1200",
                    organization_id="acme",
                    agent_id="support",
                ),
            )
        ],
    )
    """

    inbox_item_id: typing_extensions.Annotated[EntityIdBase, FieldMetadata(alias="inboxItemId")] = pydantic.Field()
    """
    ID that uniquely identifies this inbox item
    """

    status: InboxItemStatus = pydantic.Field()
    """
    Status of the inbox item.
    """

    severity: InboxItemSeverity = pydantic.Field()
    """
    Severity of the inbox item.
    """

    metadata: typing.Dict[str, str] = pydantic.Field()
    """
    Additional metadata associated with the inbox item.
    """

    title: str = pydantic.Field()
    """
    Title of the inbox item.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the inbox item.
    """

    external_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="externalUrl")] = (
        pydantic.Field(default=None)
    )
    """
    An optional URL that can be associated with the inbox item.
    """

    assignee: typing.Optional[ScopedEntity] = pydantic.Field(default=None)
    """
    An optional assignee for the inbox item.
    """

    references: typing.Optional[typing.List[ScopedEntity]] = pydantic.Field(default=None)
    """
    An optional list of references to other entities that are related to this inbox item.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
