# This file was auto-generated by Fern from our API Definition.

from .ask_request import AskRequest
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class GenerateObjectRequest(AskRequest):
    schema_: typing_extensions.Annotated[str, FieldMetadata(alias="schema")] = pydantic.Field()
    """
    JSON schema string defining the expected object shape.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
