# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .intelligent_field_search_condition import IntelligentFieldSearchCondition


class IntelligentFieldFilter(UniversalBaseModel):
    """
    Filter conversations by intelligent field values. All conditions are ANDed.
    """

    conditions: typing.List[IntelligentFieldSearchCondition] = pydantic.Field()
    """
    List of conditions to filter by. All conditions must match (AND logic).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
