# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id_filter import EntityIdFilter
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .intelligent_field_operator import IntelligentFieldOperator


class IntelligentFieldSearchCondition(UniversalBaseModel):
    """
    A single condition on an intelligent field value.
    """

    field_id: typing_extensions.Annotated[EntityIdFilter, FieldMetadata(alias="fieldId")] = pydantic.Field()
    """
    The intelligent field to filter on (referenceId + appId)
    """

    operator: IntelligentFieldOperator = pydantic.Field()
    """
    The comparison operator to apply
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The value to compare against. Required for all operators except EXISTS and NOT_EXISTS. For BOOLEAN fields use "true" or "false". For NUMBER fields use a numeric string.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
