# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .ask_stream_action_event import AskStreamActionEvent
from .ask_stream_end_event import AskStreamEndEvent
from .ask_stream_metadata_event import AskStreamMetadataEvent
from .ask_stream_start_event import AskStreamStartEvent
from .ask_stream_text_event import AskStreamTextEvent

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class StreamResponse_Text(AskStreamTextEvent):
    event_type: typing.Literal["text"] = pydantic.Field(alias="eventType", default="text")

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class StreamResponse_Action(AskStreamActionEvent):
    event_type: typing.Literal["action"] = pydantic.Field(alias="eventType", default="action")

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class StreamResponse_Metadata(AskStreamMetadataEvent):
    event_type: typing.Literal["metadata"] = pydantic.Field(alias="eventType", default="metadata")

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class StreamResponse_Start(AskStreamStartEvent):
    event_type: typing.Literal["start"] = pydantic.Field(alias="eventType", default="start")

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class StreamResponse_End(AskStreamEndEvent):
    event_type: typing.Literal["end"] = pydantic.Field(alias="eventType", default="end")

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


StreamResponse = typing.Union[
    StreamResponse_Text, StreamResponse_Action, StreamResponse_Metadata, StreamResponse_Start, StreamResponse_End
]
