# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .conversation_numeric_metric import ConversationNumericMetric


class ConversationPercentile(ConversationNumericMetric):
    """
    Calculates specified percentile for a numeric field.

    A group with no conversations in it has no percentile. Those results are omitted rather than
    reported as a value: the chart series has no point for that interval or bucket, and the
    table row has no entry for that column.
    """

    percentile: float = pydantic.Field()
    """
    The percentile to calculate. Example: 25 computes the 25th percentile.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
