# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...conversation.types.conversation_field import ConversationField
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .row_identifier_base import RowIdentifierBase


class ConversationRowIdentifier(RowIdentifierBase):
    field: ConversationField = pydantic.Field()
    """
    Field this grouping was on.
    """

    intelligent_field_id: typing_extensions.Annotated[
        typing.Optional[EntityId], FieldMetadata(alias="intelligentFieldId")
    ] = pydantic.Field(default=None)
    """
    Which intelligent field this grouping was on, set when `field` is `IntelligentField`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
