# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...conversation.types.feedback_field import FeedbackField
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .feedback_row_identifier import FeedbackRowIdentifier
from .field_value import FieldValue
from .row_base import RowBase


class FeedbackRow(RowBase):
    identifier: typing.Dict[FeedbackField, FieldValue] = pydantic.Field()
    """
    Keyed by field, so it cannot represent two groupings that share a key - notably two
    intelligent fields. Use `identifiers`, which carries one entry per grouping in request
    order.
    """

    identifiers: typing.List[FeedbackRowIdentifier] = pydantic.Field()
    """
    One entry per grouping, in the order the groupings were requested.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
