# This file was auto-generated by Fern from our API Definition.

from ...commons.types.base_paginated_request import BasePaginatedRequest
import typing
from .event_field import EventField
from .event_filter import EventFilter
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EventsSearchRequest(BasePaginatedRequest):
    sort: typing.Optional[EventField] = None
    filter: typing.Optional[EventFilter] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
