# This file was auto-generated by Fern from our API Definition.

from .novel_system_event_no_id import NovelSystemEventNoId
from ...commons.types.entity_id import EntityId
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class SystemEvent(NovelSystemEventNoId):
    id: EntityId = pydantic.Field()
    """
    The unique ID of the event
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
