# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EnumOption(UniversalBaseModel):
    """
    One allowed choice for a field whose value should come from a finite set. Use with
    MULTI_SELECT to constrain a list of choices, or with STRING/MULTILINE/NUMBER to make
    the field a single select.
    """

    value: str = pydantic.Field()
    """
    The value of the option
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display label for the option
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Instructions that tell the LLM when to pick this option. Up to 1200 characters. On a
    patch, an option sent without a description has its description cleared.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
