# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.base_capped_paginated_request import BaseCappedPaginatedRequest
from ...commons.types.entity_id_without_agent import EntityIdWithoutAgent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .intelligent_field_value_entity_filter import IntelligentFieldValueEntityFilter
from .intelligent_field_value_field_filter import IntelligentFieldValueFieldFilter
from .intelligent_field_value_sort_field import IntelligentFieldValueSortField


class IntelligentFieldValueSearchRequest(BaseCappedPaginatedRequest):
    field_filter: typing_extensions.Annotated[
        typing.Optional[IntelligentFieldValueFieldFilter], FieldMetadata(alias="fieldFilter")
    ] = pydantic.Field(default=None)
    """
    Filter by properties of the intelligent field definition. If not provided, returns values for all fields.
    """

    entity_filter: typing_extensions.Annotated[
        typing.Optional[IntelligentFieldValueEntityFilter], FieldMetadata(alias="entityFilter")
    ] = pydantic.Field(default=None)
    """
    Filter by properties of the target entity. If not provided, returns values across all entities.
    """

    created_after: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAfter")] = (
        pydantic.Field(default=None)
    )
    """
    Filter values computed on or after this timestamp
    """

    created_before: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdBefore")] = (
        pydantic.Field(default=None)
    )
    """
    Filter values computed on or before this timestamp
    """

    include_unknown_values: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="includeUnknownValues")
    ] = pydantic.Field(default=None)
    """
    Whether to include results where the LLM could not determine a value (value is null). Defaults to false.
    """

    sort: typing.Optional[IntelligentFieldValueSortField] = pydantic.Field(default=None)
    """
    Field to sort by. Defaults to CREATED_AT.
    """

    variant_id: typing_extensions.Annotated[typing.Optional[EntityIdWithoutAgent], FieldMetadata(alias="variantId")] = (
        pydantic.Field(default=None)
    )
    """
    Returns values of the fields in this agent variant's scope: its published snapshot plus
    its staged edits, matched by field. A value is included whichever variant's conversation
    produced it, and is named as this variant names the field. If not provided, returns
    values from all variants.
    
    To see values from the conversations pinned to a variant, filter conversations by
    `variantIds` in conversation search or the analytics APIs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
