# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...charters.types.charter_summary import CharterSummary
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ...core.serialization import FieldMetadata
from .intelligent_field_response import IntelligentFieldResponse


class IntelligentFieldDetailResponse(IntelligentFieldResponse):
    """
    Examples
    --------
    import datetime

    from mavenagi.commons import EntityId
    from mavenagi.intelligent_fields import (
        EnumOption,
        IntelligentFieldDetailResponse,
    )

    IntelligentFieldDetailResponse(
        field_id=EntityId(
            reference_id="ticket-priority",
            app_id="zendesk",
            organization_id="acme",
            agent_id="support",
            type="INTELLIGENT_FIELD",
        ),
        name="Ticket Priority",
        description="The priority of the conversation based on urgency",
        status="INACTIVE",
        entity_type="CONVERSATION",
        validation_type="STRING",
        enum_options=[
            EnumOption(
                value="HIGH",
                label="High Priority",
            ),
            EnumOption(
                value="MEDIUM",
                label="Medium Priority",
            ),
            EnumOption(
                value="LOW",
                label="Low Priority",
            ),
        ],
        definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
        created_at=datetime.datetime.fromisoformat(
            "2024-01-15 10:30:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2024-01-15 10:30:00+00:00",
        ),
        referencing_charters=[],
    )
    """

    referencing_charters: typing_extensions.Annotated[
        typing.Optional[typing.List[CharterSummary]], FieldMetadata(alias="referencingCharters")
    ] = pydantic.Field(default=None)
    """
    Charters whose attached segment precondition references this intelligent field.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.precondition_group_response import PreconditionGroupResponse  # noqa: E402, F401, I001

update_forward_refs(IntelligentFieldDetailResponse)
