# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id_without_agent import EntityIdWithoutAgent
from ...commons.types.entity_type import EntityType
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .intelligent_field_core import IntelligentFieldCore


class IntelligentFieldBase(IntelligentFieldCore):
    entity_type: typing_extensions.Annotated[EntityType, FieldMetadata(alias="entityType")] = pydantic.Field()
    """
    Target entity type for evaluation. CONVERSATION is supported, and AGENT_USER is supported for agents with user-level intelligent fields enabled. The backend will return an error for other types.
    """

    variant_id: typing_extensions.Annotated[typing.Optional[EntityIdWithoutAgent], FieldMetadata(alias="variantId")] = (
        pydantic.Field(default=None)
    )
    """
    On a request, the agent variant to stage the write in. On a response, the variant the request named, if any; absent when it named none.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
