# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .enum_option import EnumOption
from .intelligent_field_type import IntelligentFieldType


class IntelligentFieldCore(UniversalBaseModel):
    """
    The content of an intelligent field -- what it is called, and what the LLM should produce for it.
    """

    validation_type: typing_extensions.Annotated[IntelligentFieldType, FieldMetadata(alias="validationType")] = (
        pydantic.Field()
    )
    """
    The type of value this field holds. It constrains the schema the LLM is asked to fill
    and the JSON type of the computed `value`.
    
    - STRING / MULTILINE: a single string
    - MULTI_SELECT: a list of strings
    - BOOLEAN: `true` or `false`
    - NUMBER: a number
    
    For a single select, use STRING or NUMBER together with `enumOptions`.
    """

    definition: str = pydantic.Field()
    """
    Definition used by the LLM when generating this field's value
    """

    enum_options: typing_extensions.Annotated[
        typing.Optional[typing.List[EnumOption]], FieldMetadata(alias="enumOptions")
    ] = pydantic.Field(default=None)
    """
    The finite set of values this field may take. Omit to let the LLM produce any value of
    the `validationType`. Options may be added later with the patch endpoint, but not removed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
