# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.entity_id import EntityId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .intelligent_field_base import IntelligentFieldBase
from .intelligent_field_status import IntelligentFieldStatus


class IntelligentFieldResponse(IntelligentFieldBase):
    """
    Examples
    --------
    import datetime

    from mavenagi.commons import EntityId
    from mavenagi.intelligent_fields import EnumOption, IntelligentFieldResponse

    IntelligentFieldResponse(
        field_id=EntityId(
            reference_id="ticket-priority",
            app_id="zendesk",
            organization_id="acme",
            agent_id="support",
            type="INTELLIGENT_FIELD",
        ),
        name="Ticket Priority",
        description="The priority of the conversation based on urgency",
        status="INACTIVE",
        entity_type="CONVERSATION",
        validation_type="STRING",
        enum_options=[
            EnumOption(
                value="HIGH",
                label="High Priority",
            ),
            EnumOption(
                value="MEDIUM",
                label="Medium Priority",
            ),
            EnumOption(
                value="LOW",
                label="Low Priority",
            ),
        ],
        definition="The priority of the conversation based on the urgency and importance; draw from the content / messages in the conversation; must be one of HIGH, MEDIUM, or LOW.",
        created_at=datetime.datetime.fromisoformat(
            "2024-01-15 10:30:00+00:00",
        ),
        updated_at=datetime.datetime.fromisoformat(
            "2024-01-15 10:30:00+00:00",
        ),
    )
    """

    field_id: typing_extensions.Annotated[EntityId, FieldMetadata(alias="fieldId")] = pydantic.Field()
    """
    ID that uniquely identifies this intelligent field
    """

    status: IntelligentFieldStatus = pydantic.Field()
    """
    Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.
    """

    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = (
        pydantic.Field(default=None)
    )
    """
    The date and time the intelligent field was created
    """

    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = (
        pydantic.Field(default=None)
    )
    """
    The date and time the intelligent field was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
