# This file was auto-generated by Fern from our API Definition.

import typing

AdditionalDataKey = typing.Union[
    typing.Literal[
        "value",
        "previousValue",
        "name",
        "step",
        "reason",
        "errorCode",
        "errorMessage",
        "url",
        "query",
        "position",
        "amount",
        "currency",
        "channel",
        "sourceLanguage",
        "targetLanguage",
        "mimeType",
        "sizeBytes",
    ],
    typing.Any,
]
