# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .entity_id_without_agent import EntityIdWithoutAgent


class BotLogicIntelligentFieldDetail(UniversalBaseModel):
    field_id: typing_extensions.Annotated[EntityIdWithoutAgent, FieldMetadata(alias="fieldId")]
    name: str
    value: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
