# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .action_execution_param_value import ActionExecutionParamValue
from .bot_logic_action_reviewed_detail import BotLogicActionReviewedDetail


class BotLogicActionExecutedDetail(BotLogicActionReviewedDetail):
    action_parameters: typing_extensions.Annotated[
        typing.Dict[str, ActionExecutionParamValue], FieldMetadata(alias="actionParameters")
    ]
    execution_result: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="executionResult")] = None
    execution_error: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="executionError")] = None
    data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Structured data the action returned alongside its text result. Absent for actions that returned only text.
    """

    started_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="startedAt")] = (
        pydantic.Field(default=None)
    )
    """
    When the action invocation started. Absent for actions executed before per-action timing was recorded, and for an invocation that never returned — see `durationMs`.
    """

    duration_ms: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="durationMs")] = pydantic.Field(
        default=None
    )
    """
    How long the action invocation took, in milliseconds. Measures the invocation itself, not the agent's surrounding reasoning.
    
    Absent in two cases: actions executed before per-action timing was recorded, and actions whose invocation never returned a result — it timed out, or threw before completing. The second case matters when aggregating: the attempts with no duration are disproportionately the slowest ones, so a percentile computed over this field alone is biased low. Count `executionError` alongside it rather than treating absent as "fast".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
