# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .bot_logic_charter_detail import BotLogicCharterDetail


class BotLogicChartersItem(UniversalBaseModel):
    """
    Charter evaluation results for this bot response.
    """

    matched_charters: typing_extensions.Annotated[
        typing.List[BotLogicCharterDetail], FieldMetadata(alias="matchedCharters")
    ] = pydantic.Field()
    """
    Charters that matched the conversation state and were used to generate this response.
    """

    evaluation_truncated: typing_extensions.Annotated[bool, FieldMetadata(alias="evaluationTruncated")] = (
        pydantic.Field()
    )
    """
    True when too many charters fit the initial criteria and evaluation was cut short. The matchedCharters list may be incomplete.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
