# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .settings_schema_entry_base import SettingsSchemaEntryBase


class ComplexArraySettingsSchemaEntry(SettingsSchemaEntryBase):
    fields: typing.Optional["SettingsSchema"] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .one_of_settings_schema_entry import OneOfSettingsSchemaEntry  # noqa: E402, F401, I001
from .section_settings_schema_entry import SectionSettingsSchemaEntry  # noqa: E402, F401, I001
from .settings_schema import SettingsSchema  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_option import SettingsSchemaDiscriminatedUnionOption  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_options import SettingsSchemaDiscriminatedUnionOptions  # noqa: E402, F401, I001

update_forward_refs(ComplexArraySettingsSchemaEntry)
