# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .conversation_mode import ConversationMode
from .conversation_round import ConversationRound
from .conversation_state import ConversationState
from .entity_id_without_agent import EntityIdWithoutAgent
from .intelligent_field_condition import IntelligentFieldCondition
from .object_condition import ObjectCondition
from .precondition_operator import PreconditionOperator
from .response_length import ResponseLength


class ConversationPreconditionResponse_Tags(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["tags"], FieldMetadata(alias="conversationPreconditionType")
    ] = "tags"
    tags: typing.Set[str]
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_Metadata(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["metadata"], FieldMetadata(alias="conversationPreconditionType")
    ] = "metadata"
    key: str
    value: typing.Optional[str] = None
    values: typing.Optional[typing.List[str]] = None
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_ActionExecuted(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["actionExecuted"], FieldMetadata(alias="conversationPreconditionType")
    ] = "actionExecuted"
    action_id: typing_extensions.Annotated[str, FieldMetadata(alias="actionId")]
    app_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="appId")] = None
    conversation_round: typing_extensions.Annotated[
        typing.Optional[ConversationRound], FieldMetadata(alias="conversationRound")
    ] = None
    data_condition: typing_extensions.Annotated[
        typing.Optional[ObjectCondition], FieldMetadata(alias="dataCondition")
    ] = None
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_ResponseConfig(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["responseConfig"], FieldMetadata(alias="conversationPreconditionType")
    ] = "responseConfig"
    use_markdown: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="useMarkdown")] = None
    use_forms: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="useForms")] = None
    use_images: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="useImages")] = None
    is_copilot: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isCopilot")] = None
    response_length: typing_extensions.Annotated[
        typing.Optional[ResponseLength], FieldMetadata(alias="responseLength")
    ] = None
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_App(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["app"], FieldMetadata(alias="conversationPreconditionType")
    ] = "app"
    app_id: typing_extensions.Annotated[str, FieldMetadata(alias="appId")]
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_ConversationState(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["conversationState"], FieldMetadata(alias="conversationPreconditionType")
    ] = "conversationState"
    state: ConversationState
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_ConversationMode(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["conversationMode"], FieldMetadata(alias="conversationPreconditionType")
    ] = "conversationMode"
    conversation_mode: typing_extensions.Annotated[ConversationMode, FieldMetadata(alias="conversationMode")]
    operator: typing.Optional[PreconditionOperator] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationPreconditionResponse_IntelligentField(UniversalBaseModel):
    conversation_precondition_type: typing_extensions.Annotated[
        typing.Literal["intelligentField"], FieldMetadata(alias="conversationPreconditionType")
    ] = "intelligentField"
    field_id_without_agent: typing_extensions.Annotated[
        EntityIdWithoutAgent, FieldMetadata(alias="fieldIdWithoutAgent")
    ]
    name: typing.Optional[str] = None
    field_condition: typing_extensions.Annotated[IntelligentFieldCondition, FieldMetadata(alias="fieldCondition")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ConversationPreconditionResponse = typing.Union[
    ConversationPreconditionResponse_Tags,
    ConversationPreconditionResponse_Metadata,
    ConversationPreconditionResponse_ActionExecuted,
    ConversationPreconditionResponse_ResponseConfig,
    ConversationPreconditionResponse_App,
    ConversationPreconditionResponse_ConversationState,
    ConversationPreconditionResponse_ConversationMode,
    ConversationPreconditionResponse_IntelligentField,
]
