# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CsatInfo(UniversalBaseModel):
    rating: typing.Optional[float] = pydantic.Field(default=None)
    """
    The rating of the CSAT rating
    """

    max_rating: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="maxRating")] = pydantic.Field(
        default=None
    )
    """
    The max rating of the CSAT value (default 5)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
