# This file was auto-generated by Fern from our API Definition.

import typing

ErrorReason = typing.Union[
    typing.Literal[
        "VARIANT_LIVE",
        "VARIANT_NOT_ACTIVE",
        "STALE_TRAFFIC_REVISION",
        "STALE_WORKING_SET",
        "NOTHING_TO_COMMIT",
        "VARIANT_ALREADY_EXISTS",
        "CANNOT_ARCHIVE_LIVE_VARIANT",
        "VARIANT_HAS_STAGED_EDITS",
        "VARIANT_REQUIRED",
        "INTELLIGENT_FIELD_TYPE_CHANGED",
    ],
    typing.Any,
]
