# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .numeric_condition import NumericCondition
from .set_condition import SetCondition
from .string_condition import StringCondition
from .universal_condition import UniversalCondition


class FieldCondition_String(UniversalBaseModel):
    value: StringCondition
    field_validation_type: typing_extensions.Annotated[
        typing.Literal["string"], FieldMetadata(alias="fieldValidationType")
    ] = "string"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


class FieldCondition_Numeric(UniversalBaseModel):
    value: NumericCondition
    field_validation_type: typing_extensions.Annotated[
        typing.Literal["numeric"], FieldMetadata(alias="fieldValidationType")
    ] = "numeric"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


class FieldCondition_Boolean(UniversalBaseModel):
    """
    A condition on a single value, discriminated by the type the value is
    validated as. Used wherever a value needs testing regardless of where it
    came from: an intelligent field's computed value, or a value addressed by
    path inside data an action returned.

    Pick the variant by type:
    - `string`: For STRING and MULTILINE values
    - `numeric`: For NUMBER values
    - `boolean`: For BOOLEAN values
    - `set`: For MULTI_SELECT values (unordered set of values)

    The declared type is what the value is coerced to, not an assertion about
    how it is already stored. Action data is untyped, so a `numeric` condition
    against it coerces the same way a `numeric` intelligent field condition
    coerces a STRING field the bot was asked to answer with a number.

    For intelligent fields specifically: single select fields are represented
    as STRING/NUMBER with a list of enumOptions, and the caller is responsible
    for querying the validationType and enumOptions from the intelligent field
    API to ensure the values are valid enumOptions.
    """

    field_validation_type: typing_extensions.Annotated[
        typing.Literal["boolean"], FieldMetadata(alias="fieldValidationType")
    ] = "boolean"
    value: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class FieldCondition_Set(UniversalBaseModel):
    value: SetCondition
    field_validation_type: typing_extensions.Annotated[
        typing.Literal["set"], FieldMetadata(alias="fieldValidationType")
    ] = "set"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


class FieldCondition_Universal(UniversalBaseModel):
    value: UniversalCondition
    field_validation_type: typing_extensions.Annotated[
        typing.Literal["universal"], FieldMetadata(alias="fieldValidationType")
    ] = "universal"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


FieldCondition = typing.Union[
    FieldCondition_String, FieldCondition_Numeric, FieldCondition_Boolean, FieldCondition_Set, FieldCondition_Universal
]
