# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .conversation_kickoff_execution_response import ConversationKickoffExecutionResponse
from .conversation_response import ConversationResponse


class InitializeConversationResponse(ConversationResponse):
    """
    A conversation as returned by the `initialize` endpoint. Extends the shared
    ConversationResponse with the Conversation Kickoff result, which is only available at
    initialization time.
    """

    conversation_kickoff_results: typing_extensions.Annotated[
        typing.List[ConversationKickoffExecutionResponse], FieldMetadata(alias="conversationKickoffResults")
    ] = pydantic.Field()
    """
    Results of the Conversation Kickoffs that ran during conversation initialization, one
    entry per kickoff in the order they were recorded. Empty when no kickoff ran. Only
    present on this initialize response; other endpoints that return a conversation do not
    include it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
