# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .entity_id_without_agent import EntityIdWithoutAgent
from .intelligent_field_condition import IntelligentFieldCondition


class IntelligentFieldPrecondition(UniversalBaseModel):
    """
    A precondition based on the computed value of an intelligent field on the conversation.

    The structure of this precondition follows `LHS OP RHS`, where the LHS is
    the ID of the intelligent field (<referenceId, appId>).  Available
    operators and the corresponding types of the RHS depends on the
    validationType of the intelligent field.

    Note: in early beta, only opt-in apps and organizations/agents can
    specify intelligent field preconditions.  Otherwise, the request will be
    rejected.
    """

    field_id_without_agent: typing_extensions.Annotated[
        EntityIdWithoutAgent, FieldMetadata(alias="fieldIdWithoutAgent")
    ] = pydantic.Field()
    """
    The ID of the intelligent field.
    """

    field_condition: typing_extensions.Annotated[IntelligentFieldCondition, FieldMetadata(alias="fieldCondition")] = (
        pydantic.Field()
    )
    """
    The condition to evaluate against the field's value.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
