# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .intelligent_field_condition import IntelligentFieldCondition


class IntelligentFieldPrecondition(UniversalBaseModel):
    """
    A precondition based on the computed value of an intelligent field on the conversation.

    Note: in early beta, only opt-in apps and organizations/agents can
    specify intelligent field preconditions.  Otherwise, the request will be
    rejected.
    """

    field_reference_id: typing_extensions.Annotated[str, FieldMetadata(alias="fieldReferenceId")] = pydantic.Field()
    """
    The referenceId of the intelligent field.
    """

    field_app_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fieldAppId")] = pydantic.Field(
        default=None
    )
    """
    The appId of the intelligent field. If not provided, the calling appId will be used.
    """

    field_condition: typing_extensions.Annotated[IntelligentFieldCondition, FieldMetadata(alias="fieldCondition")] = (
        pydantic.Field()
    )
    """
    The condition to evaluate against the field's value.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
