# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .entity_id_without_agent import EntityIdWithoutAgent
from .intelligent_field_condition import IntelligentFieldCondition


class IntelligentFieldPreconditionResponse(UniversalBaseModel):
    """
    Response variant of IntelligentFieldPrecondition.
    Includes the resolved display name of the intelligent field.
    """

    field_id_without_agent: typing_extensions.Annotated[
        EntityIdWithoutAgent, FieldMetadata(alias="fieldIdWithoutAgent")
    ] = pydantic.Field()
    """
    The ID of the intelligent field.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable display name of the intelligent field. Resolved server-side.
    """

    field_condition: typing_extensions.Annotated[IntelligentFieldCondition, FieldMetadata(alias="fieldCondition")] = (
        pydantic.Field()
    )
    """
    The condition to evaluate against the field's value.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
