# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .metadata_condition import MetadataCondition


class MetadataEntryCondition(UniversalBaseModel):
    """
    A condition on the value stored under one metadata key.
    """

    key: str = pydantic.Field()
    """
    The metadata key to test. A plain key, not a path: metadata is a flat string-to-string map, so there is no nesting to address.
    """

    condition: MetadataCondition = pydantic.Field()
    """
    The condition to evaluate against the value stored under `key`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
