# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ...core.serialization import FieldMetadata
from .settings_schema_entry_base import SettingsSchemaEntryBase


class OneOfSettingsSchemaEntry(SettingsSchemaEntryBase):
    union_options: typing_extensions.Annotated[
        "SettingsSchemaDiscriminatedUnionOptions", FieldMetadata(alias="unionOptions")
    ]
    default_value: typing_extensions.Annotated[
        typing.Optional[typing.Optional[typing.Any]], FieldMetadata(alias="defaultValue")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .complex_array_settings_schema_entry import ComplexArraySettingsSchemaEntry  # noqa: E402, F401, I001
from .section_settings_schema_entry import SectionSettingsSchemaEntry  # noqa: E402, F401, I001
from .settings_schema import SettingsSchema  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_option import SettingsSchemaDiscriminatedUnionOption  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_options import SettingsSchemaDiscriminatedUnionOptions  # noqa: E402, F401, I001

update_forward_refs(OneOfSettingsSchemaEntry)
