# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .precondition_group_operator import PreconditionGroupOperator


class PreconditionGroupResponse(UniversalBaseModel):
    operator: PreconditionGroupOperator
    preconditions: typing.List["PreconditionResponse"]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .precondition_response import PreconditionResponse  # noqa: E402, F401, I001

update_forward_refs(PreconditionGroupResponse)
