# This file was auto-generated by Fern from our API Definition.

import typing

ResolutionStatus = typing.Union[
    typing.Literal[
        "UNKNOWN",
        "ERROR",
        "IN_PROGRESS",
        "RESOLVED",
        "ESCALATED",
        "INCOMPLETE",
        "NEGATIVE_FEEDBACK",
        "CONTENT_SAFETY_FLAGGED",
        "PROMPT_ATTACK_FLAGGED",
        "HANGUP",
        "INELIGIBLE",
    ],
    typing.Any,
]
