# This file was auto-generated by Fern from our API Definition.

import typing

SetRelationOperator = typing.Union[
    typing.Literal[
        "EQ",
        "NEQ",
        "CONTAINS_ANY",
        "NOT_CONTAINS_ANY",
        "CONTAINS_ALL",
        "NOT_CONTAINS_ALL",
        "SUBSET_OF",
        "NOT_SUBSET_OF",
    ],
    typing.Any,
]
