# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .visibility_type import VisibilityType


class SettingsSchemaEntryBase(UniversalBaseModel):
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the setting must have a value upon install. Defaults to false.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
