# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata
from .o_auth_authentication_method import OAuthAuthenticationMethod
from .settings_schema_validation import SettingsSchemaValidation
from .visibility_type import VisibilityType


class SettingsSchemaEntry_Text(UniversalBaseModel):
    type: typing.Literal["text"] = "text"
    default_value: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="defaultValue")] = None
    validation: typing.Optional[SettingsSchemaValidation] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Multiline(UniversalBaseModel):
    type: typing.Literal["multiline"] = "multiline"
    default_value: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="defaultValue")] = None
    validation: typing.Optional[SettingsSchemaValidation] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Array(UniversalBaseModel):
    type: typing.Literal["array"] = "array"
    default_value: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="defaultValue")
    ] = None
    validation: typing.Optional[SettingsSchemaValidation] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Complexarray(UniversalBaseModel):
    type: typing.Literal["complexarray"] = "complexarray"
    fields: typing.Optional["SettingsSchema"] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Color(UniversalBaseModel):
    type: typing.Literal["color"] = "color"
    default_value: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="defaultValue")] = None
    validation: typing.Optional[SettingsSchemaValidation] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Image(UniversalBaseModel):
    type: typing.Literal["image"] = "image"
    default_value: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="defaultValue")] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Checkbox(UniversalBaseModel):
    type: typing.Literal["checkbox"] = "checkbox"
    default_value: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="defaultValue")] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Dropdown(UniversalBaseModel):
    type: typing.Literal["dropdown"] = "dropdown"
    dropdown_options: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="dropdownOptions")]
    default_value: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="defaultValue")] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Section(UniversalBaseModel):
    type: typing.Literal["section"] = "section"
    fields: typing.Optional["SettingsSchema"] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Oauth(UniversalBaseModel):
    type: typing.Literal["oauth"] = "oauth"
    oauth_scopes: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="oauthScopes")]
    scope_labels: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.Optional[typing.Any]]], FieldMetadata(alias="scopeLabels")
    ] = None
    oauth_redirect_uri: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="oauthRedirectUri")] = (
        None
    )
    oauth_client_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="oauthClientId")] = None
    oauth_authorization_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="oauthAuthorizationUrl")
    ] = None
    oauth_client_secret: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="oauthClientSecret")] = (
        None
    )
    oauth_token_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="oauthTokenUrl")] = None
    oauth_authentication_method: typing_extensions.Annotated[
        typing.Optional[OAuthAuthenticationMethod], FieldMetadata(alias="oauthAuthenticationMethod")
    ] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_Number(UniversalBaseModel):
    type: typing.Literal["number"] = "number"
    default_value: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="defaultValue")] = None
    validation: typing.Optional[SettingsSchemaValidation] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SettingsSchemaEntry_OneOf(UniversalBaseModel):
    type: typing.Literal["oneOf"] = "oneOf"
    union_options: typing_extensions.Annotated[
        "SettingsSchemaDiscriminatedUnionOptions", FieldMetadata(alias="unionOptions")
    ]
    default_value: typing_extensions.Annotated[
        typing.Optional[typing.Optional[typing.Any]], FieldMetadata(alias="defaultValue")
    ] = None
    key: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]
    description: typing.Optional[str] = None
    visibility: typing.Optional[VisibilityType] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .complex_array_settings_schema_entry import ComplexArraySettingsSchemaEntry  # noqa: E402, F401, I001
from .one_of_settings_schema_entry import OneOfSettingsSchemaEntry  # noqa: E402, F401, I001
from .section_settings_schema_entry import SectionSettingsSchemaEntry  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_option import SettingsSchemaDiscriminatedUnionOption  # noqa: E402, F401, I001

SettingsSchemaEntry = typing.Union[
    SettingsSchemaEntry_Text,
    SettingsSchemaEntry_Multiline,
    SettingsSchemaEntry_Array,
    SettingsSchemaEntry_Complexarray,
    SettingsSchemaEntry_Color,
    SettingsSchemaEntry_Image,
    SettingsSchemaEntry_Checkbox,
    SettingsSchemaEntry_Dropdown,
    SettingsSchemaEntry_Section,
    SettingsSchemaEntry_Oauth,
    SettingsSchemaEntry_Number,
    SettingsSchemaEntry_OneOf,
]
from .settings_schema import SettingsSchema  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_options import SettingsSchemaDiscriminatedUnionOptions  # noqa: E402, F401, I001

update_forward_refs(SettingsSchemaEntry_Complexarray)
update_forward_refs(SettingsSchemaEntry_Section)
update_forward_refs(SettingsSchemaEntry_OneOf)
