# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata


class SettingsSchemaDiscriminatedUnionOption(UniversalBaseModel):
    value: str = pydantic.Field()
    """
    The value for this option (used as discriminator value)
    """

    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")] = pydantic.Field()
    """
    The display name shown in the dropdown
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional description for this option
    """

    fields: "SettingsSchema" = pydantic.Field()
    """
    The schema fields to display when this option is selected. Required fields within these fields are only validated when this option is active.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .complex_array_settings_schema_entry import ComplexArraySettingsSchemaEntry  # noqa: E402, F401, I001
from .one_of_settings_schema_entry import OneOfSettingsSchemaEntry  # noqa: E402, F401, I001
from .section_settings_schema_entry import SectionSettingsSchemaEntry  # noqa: E402, F401, I001
from .settings_schema import SettingsSchema  # noqa: E402, F401, I001
from .settings_schema_discriminated_union_options import SettingsSchemaDiscriminatedUnionOptions  # noqa: E402, F401, I001

update_forward_refs(SettingsSchemaDiscriminatedUnionOption)
