# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .string_comparison_operator import StringComparisonOperator


class StringComparisonCondition(UniversalBaseModel):
    """
    Condition comparing against a single string value
    """

    operator: StringComparisonOperator = pydantic.Field()
    """
    The comparison operator to apply
    """

    value: str = pydantic.Field()
    """
    The string value to compare against
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
