# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .string_membership_operator import StringMembershipOperator


class StringMembershipCondition(UniversalBaseModel):
    """
    Condition checking membership in a set of strings
    """

    operator: StringMembershipOperator = pydantic.Field()
    """
    The comparison operator to apply
    """

    values: typing.List[str] = pydantic.Field()
    """
    The set of string values to compare against
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
