# This file was auto-generated by Fern from our API Definition.

import typing

SystemEventName = typing.Union[
    typing.Literal[
        "APP_INSTALLED",
        "APP_UNINSTALLED",
        "APP_UPDATED",
        "NOTIFICATION_SENT",
        "NOTIFICATION_DELIVERED",
        "NOTIFICATION_FAILED",
        "INTEGRATION_CONNECTED",
        "INTEGRATION_DISCONNECTED",
        "SYNC_STARTED",
        "SYNC_COMPLETED",
        "SYNC_FAILED",
    ],
    typing.Any,
]
