# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class TextFormat_Text(UniversalBaseModel):
    """
    What form an ask's answer takes. See `AskRequest.textFormat`.
    """

    type: typing.Literal["text"] = "text"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TextFormat_JsonSchema(UniversalBaseModel):
    """
    What form an ask's answer takes. See `AskRequest.textFormat`.
    """

    type: typing.Literal["jsonSchema"] = "jsonSchema"
    schema_: typing_extensions.Annotated[typing.Optional[typing.Any], FieldMetadata(alias="schema")] = None
    description: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


TextFormat = typing.Union[TextFormat_Text, TextFormat_JsonSchema]
