# This file was auto-generated by Fern from our API Definition.

import typing

AppCategory = typing.Union[
    typing.Literal[
        "COMMUNICATION",
        "CUSTOMER_SUPPORT",
        "DATA_STORAGE",
        "INTERNAL_TOOLS",
        "KNOWLEDGE",
        "PROJECT_MANAGEMENT",
        "VOICE",
    ],
    typing.Any,
]
