# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.page import Page
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .count_by_filter_result import CountByFilterResult
from .marketplace_app import MarketplaceApp


class AppsResponse(Page):
    apps: typing.List[MarketplaceApp] = pydantic.Field()
    """
    The page of apps matching the filter.
    """

    all_apps_count_by_filter: typing_extensions.Annotated[
        typing.Optional[CountByFilterResult], FieldMetadata(alias="allAppsCountByFilter")
    ] = pydantic.Field(default=None)
    """
    How many apps fall into each visibility and category, across everything visible to the
    agent rather than just this page. Present only when `filterCountEnabled` was set.
    """

    installed_apps_count_by_filter: typing_extensions.Annotated[
        typing.Optional[CountByFilterResult], FieldMetadata(alias="installedAppsCountByFilter")
    ] = pydantic.Field(default=None)
    """
    The same breakdown restricted to apps installed on this agent. Present only when
    `filterCountEnabled` was set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
