# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .app_installed import AppInstalled
from .base_detail_app import BaseDetailApp


class MarketplaceAppDetail(BaseDetailApp):
    """
    A detailed app definition used when rendering an app detail page within the app directory.
    The instructions, installationInstructions, previewUrl have their templated values substituted with appropriate values.
    """

    installed: AppInstalled = pydantic.Field()
    """
    Whether this app is currently installed on the agent the request was scoped to.
    """

    settings: typing.Optional[typing.Optional[typing.Any]] = pydantic.Field(default=None)
    """
    The installation's stored configuration, as an object keyed by setting key. Present only
    when the app is installed on this agent. The keys mirror the app's `settingsSchema`, and a
    key is absent when it has never been set.
    
    Values nest the way the schema does: a `section` entry holds an object of its fields, a
    `oneOf` entry an object of the selected option's fields alongside its `type` discriminator,
    and a `complexarray` entry a list of such objects.
    
    Two entry types do not return what is stored:
    
    - `image` entries return a short-lived presigned download URL, never the file's bytes.
    - `oauth` entries return `accessToken` redacted, with `scopes` and `status` intact, so the
      connection still reads as connected without exposing the token.
    
    Entries the app's schema marks as sensitive are redacted: `HIDDEN` becomes `********`, and
    `PARTIALLY_VISIBLE` keeps only the last three characters (`sk-live-abc` returns as
    `********abc`). Values of three characters or fewer are left alone. OAuth access tokens are
    redacted whatever the schema says.
    
    Redacted values are safe to send back. Install compares each incoming value against the
    stored one and skips it when it is that value's redaction, so this object can be read,
    edited and written back whole without stripping anything — an untouched credential keeps
    its stored value rather than being overwritten with asterisks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...commons.types.complex_array_settings_schema_entry import ComplexArraySettingsSchemaEntry  # noqa: E402, F401, I001
from ...commons.types.one_of_settings_schema_entry import OneOfSettingsSchemaEntry  # noqa: E402, F401, I001
from ...commons.types.section_settings_schema_entry import SectionSettingsSchemaEntry  # noqa: E402, F401, I001
from ...commons.types.settings_schema import SettingsSchema  # noqa: E402, F401, I001
from ...commons.types.settings_schema_discriminated_union_option import SettingsSchemaDiscriminatedUnionOption  # noqa: E402, F401, I001
from ...commons.types.settings_schema_discriminated_union_options import SettingsSchemaDiscriminatedUnionOptions  # noqa: E402, F401, I001
