# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawVoiceClient, RawVoiceClient
from .types.voice_session_token_response import VoiceSessionTokenResponse
from .types.voice_token_type import VoiceTokenType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VoiceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVoiceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVoiceClient
        """
        return self._raw_client

    def session_token(
        self,
        *,
        app_user_id: str,
        type: VoiceTokenType,
        custom_data: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceSessionTokenResponse:
        """
        Creates a short-lived session token for authenticating voice connections.

        Supports two token types:
        - **webrtc**: A Twilio-compatible access token for browser-based WebRTC calls
        - **websocket**: An RS256 JWT for direct WebSocket connections to /v1/voice/conversations

        Session tokens are required before establishing any voice connection.

        Parameters
        ----------
        app_user_id : str
            The end user identity for the voice session.

        type : VoiceTokenType
            The type of session token to generate.
            Use "webrtc" for browser-based calls via Twilio, or "websocket" for direct WebSocket connections.

        custom_data : typing.Optional[typing.Dict[str, str]]
            Arbitrary key-value metadata to associate with this session (e.g., conversationId, topic).
            For WebRTC tokens, this data is stored server-side and referenced by a secure ID
            encoded in the token identity, ensuring it cannot be tampered with by the client.
            For WebSocket tokens, clients can also pass data directly in the Config message.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceSessionTokenResponse

        Examples
        --------
        from mavenagi import MavenAGI

        client = MavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )
        client.voice.session_token(
            app_user_id="appUserId",
            type="webrtc",
        )
        """
        _response = self._raw_client.session_token(
            app_user_id=app_user_id, type=type, custom_data=custom_data, request_options=request_options
        )
        return _response.data


class AsyncVoiceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVoiceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVoiceClient
        """
        return self._raw_client

    async def session_token(
        self,
        *,
        app_user_id: str,
        type: VoiceTokenType,
        custom_data: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VoiceSessionTokenResponse:
        """
        Creates a short-lived session token for authenticating voice connections.

        Supports two token types:
        - **webrtc**: A Twilio-compatible access token for browser-based WebRTC calls
        - **websocket**: An RS256 JWT for direct WebSocket connections to /v1/voice/conversations

        Session tokens are required before establishing any voice connection.

        Parameters
        ----------
        app_user_id : str
            The end user identity for the voice session.

        type : VoiceTokenType
            The type of session token to generate.
            Use "webrtc" for browser-based calls via Twilio, or "websocket" for direct WebSocket connections.

        custom_data : typing.Optional[typing.Dict[str, str]]
            Arbitrary key-value metadata to associate with this session (e.g., conversationId, topic).
            For WebRTC tokens, this data is stored server-side and referenced by a secure ID
            encoded in the token identity, ensuring it cannot be tampered with by the client.
            For WebSocket tokens, clients can also pass data directly in the Config message.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VoiceSessionTokenResponse

        Examples
        --------
        import asyncio

        from mavenagi import AsyncMavenAGI

        client = AsyncMavenAGI(
            organization_id="YOUR_ORGANIZATION_ID",
            agent_id="YOUR_AGENT_ID",
            app_id="YOUR_APP_ID",
            app_secret="YOUR_APP_SECRET",
        )


        async def main() -> None:
            await client.voice.session_token(
                app_user_id="appUserId",
                type="webrtc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.session_token(
            app_user_id=app_user_id, type=type, custom_data=custom_data, request_options=request_options
        )
        return _response.data
