# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_status import SegmentStatus


class SegmentFilter(UniversalBaseModel):
    """
    Filter criteria for searching segments.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter segments by name. Case-insensitive substring match.
    Empty string returns all results.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter segments by description. Case-insensitive substring match.
    Empty string returns all results.
    """

    statuses: typing.Optional[typing.List[SegmentStatus]] = pydantic.Field(default=None)
    """
    Filter segments by status. Returns segments matching any of the provided statuses.
    Empty list returns all non-deleted results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
